---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url:
sections:
  - type: heading
    label: General
  - type: document
    path: src/_data/sections.json
    label: Sections
  - type: document
    path: src/_data/header.json
    label: Header
  - type: document
    path: src/_data/contact.json
    label: Contact
  - type: document
    path: src/_data/skills.json
    label: Skills
  - type: directory
    path: src/organizations
    label: Organizations
    create: documents
    match: "**/*.json"
    new_doc_ext: json
    templates:
      - organization
  - type: heading
    label: Entries
  - type: document
    path: src/entries/titles.json
    label: Section Titles
  - type: directory
    path: src/entries/education
    label: Education
    create: documents
    match: "**/*.md"
    new_doc_ext: md
    templates:
      - entry
  - type: directory
    path: src/entries/research
    label: Research
    create: documents
    match: "**/*.md"
    new_doc_ext: md
    templates:
      - entry
  - type: directory
    path: src/entries/teaching
    label: Teaching
    create: documents
    match: "**/*.md"
    new_doc_ext: md
    templates:
      - entry
  - type: directory
    path: src/entries/talks
    label: Talks
    create: documents
    match: "**/*.md"
    new_doc_ext: md
    templates:
      - entry
  - type: directory
    path: src/entries/grants
    label: Grants
    create: documents
    match: "**/*.md"
    new_doc_ext: md
    templates:
      - entry
  - type: directory
    path: src/entries/outreach
    label: Outreach
    create: documents
    match: "**/*.md"
    new_doc_ext: md
    templates:
      - entry
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ""
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm start
