---
new_page_extension: md
auto_deploy: false
admin_path:
webhook_url:
sections:
  - type: document
    path: src/_data/general.json
    label: General
  - type: directory
    path: src/organizations
    label: Organizations
    create: documents
    match: "**/*.md"
    new_doc_ext: md
    templates:
      - organization
  - type: heading
    label: Sections
  - type: document
    path: src/_data/sections.json
    label: Order and Titles
  - type: directory
    path: src/entries/education
    label: Education
    create: documents
    match: "**/*"
    templates:
      - entry
  - type: directory
    path: src/entries/research
    label: Research
    create: documents
    match: "**/*"
    templates:
      - entry
  - type: directory
    path: src/entries/teaching
    label: Teaching
    create: documents
    match: "**/*"
    templates:
      - entry
  - type: document
    path: src/_data/skills.json
    label: Skills
upload_dir: src/images
public_path: dist/images
front_matter_path: ""
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
