---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url:
sections:
  - type: document
    label: General
    path: src/_data/general.json
  - type: document
    label: Header
    path: src/_data/header.json
  - type: document
    label: Contact
    path: src/_data/contact.json
  - type: document
    label: Skills
    path: src/_data/skills.json
  - type: directory
    path: src/entries
    label: Entries
    create: documents
    match: "**/*.md"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ""
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm start
