---
label: Configuration
hide_body: true
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: type
  type: select
  default: []
  config:
    required: true
    options:
    - education
    - experience
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Type
  description: Needed for SEO
