---
label: Configuration
hide_body: true
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
  description: What is the section title for these entries
- name: type
  type: select
  default: []
  config:
    required: true
    options: []
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Type
  description: Type of entry (for SEO)
- name: order
  type: list
  config:
    use_select: true
    min: 
    max: 
    source:
      type: pages
      section: outreach
  label: Order
